# Generated by Django 4.2 on 2024-09-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_image_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="articles.article",
            ),
        ),
    ]
