# Generated by Django 4.2 on 2024-09-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="articles.article",
            ),
        ),
    ]
