# Generated by Django 4.2 on 2024-09-17 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blinded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blinders', to=settings.AUTH_USER_MODEL)),
                ('blinder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blinding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blinder', 'blinded')},
            },
        ),
    ]
